name: tdd_boilerplate_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cli_completion: ^0.3.0
  collection: ^1.18.0
  glob: ^2.1.2
  lcov_parser: ^0.1.2
  mason: ^0.1.0-dev.50
  mason_logger: ^0.2.8
  meta: ^1.9.1
  pub_updater: ^0.3.1
  pubspec_parse: ^1.2.3
  stack_trace: ^1.11.1
  universal_io: ^2.2.2
  very_good_test_runner: ^0.1.2

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0+1
